### ISSUE TITLE
v1.4.0-beta01 fails to open on macOS aarch64

### ISSUE THREAD

**Issue by yougotwill** [JetpackDuba/Gitnuro#232]
Hi, happy to see a new release incoming. I downloaded the beta and when i try to open it the app opens but nothing is rendered on the screen and then it quits itself.

I'm on an M3 max with macOS 14.6.1 (23G93).

Running binary logs the following info:

```
LOG] OS - OS is mac os x
log4j:WARN No appenders could be found for logger (org.slf4j).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Exception in thread "main" java.lang.UnsatisfiedLinkError: /Users/will/Library/Application/gitnuro/tmp/libgitnuro_rs.dylib: dlopen(/Users/will/Library/Application/gitnuro/tmp/libgitnuro_rs.dylib, 0x0001): tried: '/Users/will/Library/Application/gitnuro/tmp/libgitnuro_rs.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/will/Library/Application/gitnuro/tmp/libgitnuro_rs.dylib' (no such file), '/Users/will/Library/Application/gitnuro/tmp/libgitnuro_rs.dylib' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at com.jetpackduba.gitnuro.App.initNativeDependencies(App.kt:189)
	at com.jetpackduba.gitnuro.App.start(App.kt:90)
	at com.jetpackduba.gitnuro.MainKt.main(main.kt:9)
Failed to launch JVM
```

I guess the build is Intel only but usually mac will still run the app using Rosetta. I have other apps that are built for Intel and run normally. I guess I will have to wait until aarch64 builds are fixed.

**Comment by JetpackDuba** [comment]
Hey! Thank you for your report!

I think the issue could be related to the CI process. I've updated the MacOS zip and it's checksum, it seems to work fine now.

**Comment by yougotwill** [comment]
Confirm it now works! Thank you. Closing
