### ISSUE TITLE
Certain characters break SSH config parsing

### ISSUE THREAD

**Issue by ProjectInfinity** [JetpackDuba/Gitnuro#28]
Currently there seems to be a bug related to ssh config parsing in one of the libraries that Gitnuro uses, this causes connections to fail (at least when using a SSH remote) while the character is present.

**To Reproduce**
1. Have a invalid character for the parser in ssh config hostname. Example: user@server.com
2. Attempt to do any action that interacts with the remote.

**Expected behavior**
The action should succeed, instead it fails with a hangup and a parsing error.

**Logs**
Some information have been slightly altered to hide sensitive information.

```
org.eclipse.jgit.api.errors.TransportException: git@server.com:Organisation/repo.git: remote hung up unexpectedly
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:244)
        at com.jetpackduba.gitnuro.git.remote_operations.FetchAllBranchesUseCase$invoke$2.invokeSuspend(FetchAllBranchesUseCase.kt:27)
        at com.jetpackduba.gitnuro.git.remote_operations.FetchAllBranchesUseCase$invoke$2.invoke(FetchAllBranchesUseCase.kt)
        at com.jetpackduba.gitnuro.git.remote_operations.FetchAllBranchesUseCase$invoke$2.invoke(FetchAllBranchesUseCase.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at com.jetpackduba.gitnuro.git.remote_operations.FetchAllBranchesUseCase.invoke(FetchAllBranchesUseCase.kt:13)
        at com.jetpackduba.gitnuro.viewmodels.MenuViewModel$fetchAll$1.invokeSuspend(MenuViewModel.kt:33)
        at com.jetpackduba.gitnuro.viewmodels.MenuViewModel$fetchAll$1.invoke(MenuViewModel.kt)
        at com.jetpackduba.gitnuro.viewmodels.MenuViewModel$fetchAll$1.invoke(MenuViewModel.kt)
        at com.jetpackduba.gitnuro.git.TabState$safeProcessing$1$2.invokeSuspend(TabState.kt:71)
        at com.jetpackduba.gitnuro.git.TabState$safeProcessing$1$2.invoke(TabState.kt)
        at com.jetpackduba.gitnuro.git.TabState$safeProcessing$1$2.invoke(TabState.kt)
        at com.jetpackduba.gitnuro.extensions.StateManagementUtilsKt.delayedStateChange(StateManagementUtils.kt:21)
        at com.jetpackduba.gitnuro.git.TabState$safeProcessing$1.invokeSuspend(TabState.kt:65)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: org.eclipse.jgit.errors.TransportException: git@server.com:Organisation/repo.git: remote hung up unexpectedly
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:313)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:153)
        at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:151)
        at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:103)
        at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1405)
        at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:233)
        ... 23 more
Caused by: java.io.IOException: java.lang.IllegalArgumentException: Invalid host pattern char in user@server.com
        at org.apache.sshd.client.config.hosts.ConfigFileHostEntryResolver.resolveEffectiveHost(ConfigFileHostEntryResolver.java:72)
        at org.apache.sshd.client.SshClient.resolveHost(SshClient.java:660)
        at org.apache.sshd.client.SshClient.connect(SshClient.java:538)
        at org.apache.sshd.client.session.ClientSessionCreator.connect(ClientSessionCreator.java:74)
        at org.apache.sshd.client.session.ClientSessionCreator.connect(ClientSessionCreator.java:57)
        at com.jetpackduba.gitnuro.credentials.GRemoteSession.setup(GRemoteSession.kt:80)
        at com.jetpackduba.gitnuro.credentials.GSessionManager$generateSshSessionFactory$1.getSession(GSessionManager.kt:23)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:107)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:281)
        ... 28 more
Caused by: java.lang.IllegalArgumentException: Invalid host pattern char in user@server.com
        at org.apache.sshd.common.util.ValidateUtils.createFormattedException(ValidateUtils.java:213)
        at org.apache.sshd.common.util.ValidateUtils.throwIllegalArgumentException(ValidateUtils.java:179)
        at org.apache.sshd.common.util.ValidateUtils.checkTrue(ValidateUtils.java:168)
        at org.apache.sshd.client.config.hosts.HostPatternsHolder.toPattern(HostPatternsHolder.java:293)
        at org.apache.sshd.client.config.hosts.HostPatternsHolder.parsePatterns(HostPatternsHolder.java:246)
        at org.apache.sshd.client.config.hosts.HostConfigEntry.setHost(HostConfigEntry.java:173)
        at org.apache.sshd.client.config.hosts.HostConfigEntry.readHostConfigEntries(HostConfigEntry.java:939)
        at org.apache.sshd.client.config.hosts.HostConfigEntry.readHostConfigEntries(HostConfigEntry.java:867)
        at org.apache.sshd.client.config.hosts.HostConfigEntry.readHostConfigEntries(HostConfigEntry.java:861)
        at org.apache.sshd.client.config.hosts.HostConfigEntry.readHostConfigEntries(HostConfigEntry.java:848)
        at org.apache.sshd.client.config.hosts.ConfigFileHostEntryResolver.reloadHostConfigEntries(ConfigFileHostEntryResolver.java:100)
        at org.apache.sshd.client.config.hosts.DefaultConfigFileHostEntryResolver.reloadHostConfigEntries(DefaultConfigFileHostEntryResolver.java:84)
        at org.apache.sshd.client.config.hosts.ConfigFileHostEntryResolver.resolveEffectiveResolver(ConfigFileHostEntryResolver.java:84)
        at org.apache.sshd.client.config.hosts.ConfigFileHostEntryResolver.resolveEffectiveHost(ConfigFileHostEntryResolver.java:59)
        ... 36 more
LastError flow: Error(date=1667308442593, exception=org.eclipse.jgit.api.errors.TransportException: git@server.com:Organisation/repo.git: remote hung up unexpectedly, message=git@server.com:Organisation/repo.git: remote hung up unexpectedly)
TabViewModel - Refreshing repository state SAFE`

**Comment by JetpackDuba** [comment]
Can you please test again with Gitnuro 1.2.0?

**Comment by ProjectInfinity** [comment]
It works and it doesn't.

What works:
Any action that interacts with SSH.

What doesn't:
It's asking me for a PEM pass phrase in the terminal and gets stuck there until I enter the information there, no password is asked for in the application.

If I start the application by clicking the JAR and not from a terminal it is forever stuck since it does not let me enter the password.

```
2023-05-10 10:09:52 INFO  slf4j:8 - OS - OS is linux
2023-05-10 10:09:52 INFO  slf4j:8 - TabViewModel - Trying to open repository -- censored repository information --
2023-05-10 10:09:52 INFO  slf4j:8 - TabViewModel - Refreshing repository state SAFE
2023-05-10 10:09:54 INFO  slf4j:8 - OS - OS is linux
2023-05-10 10:10:02 INFO  EdDSASecurityProviderRegistrar:112 - getOrCreateProvider(EdDSA) created instance of net.i2p.crypto.eddsa.EdDSASecurityProvider
Enter PEM pass phrase:
```

**Comment by JetpackDuba** [comment]
That's start at least.

Can I know more about your setup, please? Or if you could provide a dummy example of your config to try to create something similar.

**Comment by ProjectInfinity** [comment]
Very basic setup.

I have a OpenSSH private key with a passphrase (generated with ssh-keygen -t rsa)

Then in my ssh config file I have something simple like this:
```
Host username@example.com
HostName example.com
User username
Port 22
```

**Comment by JetpackDuba** [comment]
That's weird, I've got an identical setup that works as expected (Using master version instead of 1.2.0, because there is a bug related to RSA support in the last release). The weird part is the PEM certificate request, does the same question show up when using the CLI?

**Comment by ProjectInfinity** [comment]
What do you mean? If using a passphrase the git cli will ask for it yes, but the output is different so this is likely from the new ssh library

**Comment by JetpackDuba** [comment]
I was simply wondering if it was asking specifically the PEM password or what. Just to see if the output was perhaps different than what I was getting using CLI, but w/e, it would be better to have more detailed logs.

Can you give a try to the sshLogs branch that I've pushed? LibSSH logs are enabled in that branch, I'd like to see if I'm missing something.

**Comment by ProjectInfinity** [comment]
So it works just fine using gradlew run, it does however never ask for password in the release, from neither flatpak nor JAR.

**Comment by JetpackDuba** [comment]
Weird. Does v1.2.1 also ask for the password?

**Comment by ProjectInfinity** [comment]
The flatpak and JAR does not (however the terminal does ask for password if started from the terminal).

I noticed one more thing now. I can enter whatever I want as password in the terminal (doesn't matter if it is correct or not) but once it passes this enter password prompt, Gitnuro shows the interface for entering password. 

Running 1.2.1 from main branch using gradlew run works as expected but I think I figured out why.
It seems like LibSSH fails when running from gradlew run but not when running in flatpak/jar.

See logs from gradlew run:
> Task :run
2023-05-16 13:20:36 INFO  slf4j:8 - OS - OS is linux
2023-05-16 13:20:36 INFO  slf4j:8 - TabViewModel - Trying to open repository /home/USER/censored
2023-05-16 13:20:36 INFO  slf4j:8 - TabViewModel - Refreshing repository state SAFE
2023-05-16 13:20:38 INFO  slf4j:8 - OS - OS is linux
2023-05-16 13:20:45 INFO  EdDSASecurityProviderRegistrar:112 - getOrCreateProvider(EdDSA) created instance of net.i2p.crypto.eddsa.EdDSASecurityProvider
Enter PEM pass phrase:
Enter PEM pass phrase:
2023-05-16 13:20:45 ERROR slf4j:16 - LibSshSession - Result is: 1.
Error is: Failed to read private key: /home/USER/.ssh/id_rsa

So since LibSSH fails from gradlew it looks like it works by skipping the waiting on passphrase in terminal and instead asking in the GUI.

**Comment by JetpackDuba** [comment]
I've force pushed the sshLogs branch (rebased main branch) and added one more change, would you mind testing, please?

Instead of passing a NULL password to `ssh_userauth_publickey_auto`, it now passes an empty string, because the docs says:

> Use this passphrase to unlock the privatekey. Use NULL if you don't want to use a passphrase or **the user should be asked**.

Passing an empty string still works for SSH keys without password, so I hope it also prevents the pwd being asked from the CLI.

**Comment by JetpackDuba** [comment]
Great! Thanks for helping testing :smile: 

About the password being asked, yes, it is somewhat intentional. I want to address it during 1.3.0 if possible, for SSH and for HTTP auth.
