### ISSUE TITLE
Failed to push :  Invalid credentials helper: "store" is not yet supported

### ISSUE THREAD

**Issue by pdefert** [JetpackDuba/Gitnuro#46]
**Describe the bug**
our gitlab server is protected by SSO OpenidConnect
With git cli no problem to connect , we use personal token as password

but  in gitnuro we dhave not provide any credentials and we have this error when we want to push commit
<pre>
com.jetpackduba.gitnuro.exceptions.NotSupportedHelper: Invalid credentials helper: "store" is not yet supported
	at com.jetpackduba.gitnuro.credentials.HttpCredentialsProvider.getExternalCredentialsHelper(HttpCredentialsProvider.kt:207)
	at com.jetpackduba.gitnuro.credentials.HttpCredentialsProvider.get(HttpCredentialsProvider.kt:42)
	at org.eclipse.jgit.transport.HttpAuthMethod.authorize(HttpAuthMethod.java:205)
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:683)
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:627)
	at org.eclipse.jgit.transport.TransportHttp.openPush(TransportHttp.java:541)
	at org.eclipse.jgit.transport.PushProcess.execute(PushProcess.java:138)
	at org.eclipse.jgit.transport.Transport.push(Transport.java:1473)
	at org.eclipse.jgit.api.PushCommand.call(PushCommand.java:149)
	at com.jetpackduba.gitnuro.git.remote_operations.PushBranchUseCase$invoke$2.invokeSuspend(PushBranchUseCase.kt:26)
	at com.jetpackduba.gitnuro.git.remote_operations.PushBranchUseCase$invoke$2.invoke(PushBranchUseCase.kt)
	at com.jetpackduba.gitnuro.git.remote_operations.PushBranchUseCase$invoke$2.invoke(PushBranchUseCase.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.jetpackduba.gitnuro.git.remote_operations.PushBranchUseCase.invoke(PushBranchUseCase.kt:14)
	at com.jetpackduba.gitnuro.viewmodels.MenuViewModel$push$1.invokeSuspend(MenuViewModel.kt:40)
	at com.jetpackduba.gitnuro.viewmodels.MenuViewModel$push$1.invoke(MenuViewModel.kt)
	at com.jetpackduba.gitnuro.viewmodels.MenuViewModel$push$1.invoke(MenuViewModel.kt)
	at com.jetpackduba.gitnuro.git.TabState$safeProcessing$1$2.invokeSuspend(TabState.kt:73)
	at com.jetpackduba.gitnuro.git.TabState$safeProcessing$1$2.invoke(TabState.kt)
	at com.jetpackduba.gitnuro.git.TabState$safeProcessing$1$2.invoke(TabState.kt)
	at com.jetpackduba.gitnuro.extensions.StateManagementUtilsKt.delayedStateChange(StateManagementUtils.kt:21)
	at com.jetpackduba.gitnuro.git.TabState$safeProcessing$1.invokeSuspend(TabState.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
LastError flow: Error(date=1669201149734, exception=com.jetpackduba.gitnuro.exceptions.NotSupportedHelper: Invalid credentials helper: "store" is not yet supported, message=Invalid credentials helper: "store" is not yet supported)

</pre>

**Desktop :**
 - OS:  Linux ubuntu
 - Version [22.04]

**Comment by JetpackDuba** [comment]
It's an intentional error. Your .gitconfig specifies credentials helper has "store" as value, which is not yet supported.

I've never heard of SSO OpenidConnect so I'm not really sure how does it affect Gitnuro's behavior.

There are multiple workarounds for this:
- Using SSH instead of HTTP.
- Use Git Credentials Manager and set the path in your .gitconfig file as shown in the last question of the [FAQ](https://github.com/JetpackDuba/Gitnuro#faq).
- Simply remove the credentials helper from your .gitconfig (not recomended as it would ask you everytime the username+password).

It's not the ideal solution but not much more can be done until I rework all the credentials handling.
