### ISSUE TITLE
Unable to open existing (local) repositories.

### ISSUE THREAD

**Issue by Escain** [JetpackDuba/Gitnuro#58]
**Describe the bug**
On a new tab, I click on "Open a repository", navigate and select the already existing repository, and click "open". 
An error appear and I can't open the repo. The repo are fine using "git" command line, and other clients.

The java error shows:
```
SystemDialogs - IsZenityInstalled true
TabViewModel - Trying to open repository /home/...../MyProject
org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index
        at org.eclipse.jgit.lib.Repository.getWorkTree(Repository.java:1573)
        at com.jetpackduba.gitnuro.viewmodels.TabViewModel$openRepository$1.invokeSuspend(TabViewModel.kt:164)
        at com.jetpackduba.gitnuro.viewmodels.TabViewModel$openRepository$1.invoke(TabViewModel.kt)
        at com.jetpackduba.gitnuro.viewmodels.TabViewModel$openRepository$1.invoke(TabViewModel.kt)
        at com.jetpackduba.gitnuro.git.TabState$safeProcessingWithoutGit$1.invokeSuspend(TabState.kt:100)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
LastError flow: Error(date=1671283726874, exception=org.eclipse.jgit.errors.NoWorkTreeException: Bare Repository has neither a working tree, nor an index, message=Bare Repository has neither a working tree, nor an index)
```

**To Reproduce**
1. Run the application: java -jar Gitnuro.....jar
2. On a new tab, click on "Open a repository"
3. Navigate to the cloned, non-bar repository. (cloned with git clone https:...... MyProject)

**Expected behavior**
Eventually, see the repository open in the GUI.

**Screenshots**
![image](https://user-images.githubusercontent.com/10837802/208244600-22c93678-bee9-48f2-8801-d6d9e3503a26.png)

![image](https://user-images.githubusercontent.com/10837802/208244639-702ebc63-4f95-4678-b9dd-7da2f1d5609c.png)

**Desktop (please complete the following information):**
 - OS: Debian 11, on kernel 5.10.0-19-amd64
 - KDE Plasma desktop 5.20.5
 - OpenSDK 17.0.4

**Comment by JetpackDuba** [comment]
Hello! Thanks for your report @Escain 😄 

Does it happen with any repository or just this one in specific? Does it also happen if you clone it from Gitnuro itself?

**Comment by Escain** [comment]
Hi @JetpackDuba,
I made some extensive tests and found the following:

I have a hierarchy of git repositories: Main, including several subprojects as `git submodules`.

When creating those project using:
`git clone MySubmodule` all works fine, and I can open them with Gitnuro.

However, when I create them using:
`git submodule update --init --recursive`

The `.git` folder is actually just a file, not a folder. The content of that ".git" file is something like:

`gitdir: ../../.git/modules/src/MySubModule`

There, all the `.git` content is present, as in usual repos.

So, probably just that submodules repos are not suported yet (which I did not know that submodules where differently handled).

**Comment by JetpackDuba** [comment]
Oh, nice. Thanks for the detailed explanation and testing!

As you mentioned, submodules work differently than normal repositories. I've planned adding support to submodules in 1.2. Issue https://github.com/JetpackDuba/Gitnuro/issues/29 is about it in case you want to follow it.
