### ISSUE TITLE
Unable to push/pull Gitlab repositories using Git credentials manager

### ISSUE THREAD

**Issue by miroirdelame** [JetpackDuba/Gitnuro#95]
**Describe the bug**
I have two repositories stored on Gitlab. I've successfully set up git-credentials-manager (gut pull / push on command line works well)
When I click on "Push" or "Pull" in the app, I always get an "Authentification not supported" error

Here is the log that displays on the command line :
`org.eclipse.jgit.api.errors.TransportException: https://gitlab.com/my-repo.git: authentication not supported
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:244)
	at org.eclipse.jgit.api.PullCommand.call(PullCommand.java:266)
	at com.jetpackduba.gitnuro.git.remote_operations.PullBranchUseCase$invoke$2.invokeSuspend(PullBranchUseCase.kt:19)
	at com.jetpackduba.gitnuro.git.remote_operations.PullBranchUseCase$invoke$2.invoke(PullBranchUseCase.kt)
	at com.jetpackduba.gitnuro.git.remote_operations.PullBranchUseCase$invoke$2.invoke(PullBranchUseCase.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:89)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.jetpackduba.gitnuro.git.remote_operations.PullBranchUseCase.invoke(PullBranchUseCase.kt:13)
	at com.jetpackduba.gitnuro.viewmodels.MenuViewModel$pull$1.invokeSuspend(MenuViewModel.kt:26)
	at com.jetpackduba.gitnuro.viewmodels.MenuViewModel$pull$1.invoke(MenuViewModel.kt)
	at com.jetpackduba.gitnuro.viewmodels.MenuViewModel$pull$1.invoke(MenuViewModel.kt)
	at com.jetpackduba.gitnuro.git.TabState$safeProcessing$1$2.invokeSuspend(TabState.kt:73)
	at com.jetpackduba.gitnuro.git.TabState$safeProcessing$1$2.invoke(TabState.kt)
	at com.jetpackduba.gitnuro.git.TabState$safeProcessing$1$2.invoke(TabState.kt)
	at com.jetpackduba.gitnuro.extensions.StateManagementUtilsKt.delayedStateChange(StateManagementUtils.kt:21)
	at com.jetpackduba.gitnuro.git.TabState$safeProcessing$1.invokeSuspend(TabState.kt:67)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: org.eclipse.jgit.errors.TransportException: https://gitlab.com/my-repo.git: authentication not supported
	at org.eclipse.jgit.transport.TransportHttp.connect(TransportHttp.java:674)
	at org.eclipse.jgit.transport.TransportHttp.openFetch(TransportHttp.java:465)
	at org.eclipse.jgit.transport.FetchProcess.executeImp(FetchProcess.java:151)
	at org.eclipse.jgit.transport.FetchProcess.execute(FetchProcess.java:103)
	at org.eclipse.jgit.transport.Transport.fetch(Transport.java:1405)
	at org.eclipse.jgit.api.FetchCommand.call(FetchCommand.java:233)
	... 24 more
LastError flow: Error(date=1681215817142, exception=org.eclipse.jgit.api.errors.TransportException: https://gitlab.com/my-repo.git: authentication not supported, message=https://gitlab.com/my-repo.git: authentication not supported)
TabViewModel - Refreshing repository state SAFE`

**To Reproduce**

1. Set up a GitLab repository by other means
2. Import the repository into Gitnuro
3. Click on "Push" or "Pull"

**Expected behavior**
No error, push / pull should work

**Desktop (please complete the following information):**

- OS: Debian 11
- Version 1.1.1

**Comment by miroirdelame** [comment]
It works with the Java version but not with the flatpak's one.
My issue seems to be a duplicate of https://github.com/flathub/com.jetpackduba.Gitnuro/issues/6. I close it
